### PR TITLE
use local rather than session storage for auth directs

### LINKED ISSUE #305: WEB-059 Cannot login to the website
What is the bug?: Cannot login to the website
Severity: high
Steps to reproduce: go to the website and try to access the dashboard, telling  it to login with your Discord account
Browser: Chrome version 84.0.4147.89
System: Android 10, build QQ3A.200705.002
Context: trying to login gives "Invalid OAuth state" error, even after clearing cache and restarting browser

- R to the Ichie#6193
Verification: 0

### PR DESCRIPTION
**Pull request by mommothazaz123**
Expected flow: 
```
TAB 1  front page - log in - discord - accept - /login - requested page
```

Actual flow on Android Chrome
```
TAB 1  front page - log in - front page
Discord App                \ discord - accept
TAB 2                                         \ /login (error)
```

This PR changes the storage of the expected OAuth state to use localStorage rather than sessionStorage since sessionStorage is not shared between Tab 1 and Tab 2 on the Android flow.

Fixes #305

### CODE REVIEW

File: src/app/SecurityHelper.ts [hunk 1]
```diff
@@ -9,9 +9,10 @@ const scope = encodeURIComponent(oAuthScope);
 
 /// generates and saves an oauth state to sessionStorage (oauth-state) and returns url of discord oauth
 export function navigateToDiscordOauth() {
-  // set oauth state in session storage
+  // set oauth state in local storage
+  // Discord OAuth2 opens a new tab on Android Chrome, so we use localStorage instead of sessionStorage
   const state = generateOauthState();
-  sessionStorage.setItem('oauth-state', state);
+  localStorage.setItem('expected-oauth-state', state);
```
Comment (justinryder) [inline src/app/SecurityHelper.ts:15]: You might want to wrap local storage accessors in some util that will try catch around them and ensure the calling logic can handling missing data. Depending on browser, user settings, private browsing mode, these can error even on supporting browsers.

Here's the utils I use that include comments detailing the reasons they may error:
https://github.com/DnDBeyond/ddb-character-listing-client/blob/master/src/LocalStorageUtils.js
